### ISSUE TITLE
公司官网静态页面大背景拼接和移动端背景变形问题

### ISSUE THREAD

**Issue by qqccyv** [qqccyv/blog#34]
## 今天写公司官网静态页面的时候遇到了两个问题：
> 1.某一页面是一个超大的背景图片，但是UI给的背景图是三段式的，并且和功能模块并不匹配，对背景的设置造成了一定的麻烦。

![image](https://user-images.githubusercontent.com/54464085/82139626-c43d0280-985b-11ea-8d94-d9ed66e46393.png)

> 2. 虽然公司的页面没要求做移动端，但是要求至少正常显示，而由于官网布局是中心width：1200px居中，占位盒子width：100%的布局，在切换到移动端页面的时候背景图会因为视口的变化而变形

![image](https://user-images.githubusercontent.com/54464085/82139591-6d372d80-985b-11ea-8a23-6aa621419214.png)

#### 1. CSS3中可以对背景图进行多图设置，并且可以设置每份背景图的位置,通过设置背景图在body中的位置，来使引入的背景图从上到下依次展示

```css
// 拼接背景图
body {
  min-width: 1200px;
  background-image: url(../images/Saas-top.jpg), // 用逗号将多段背景图隔开设置
              url(../images/Saas-second.png),
              url(../images/Saas-middle.jpg),
              url(../images/Saas-fourth.png),
              url(../images/Saas-bottom.jpg);
  background-repeat: no-repeat,no-repeat,no-repeat,no-repeat,no-repeat; // 设置不重复拼接
  background-position: 0 0,0 919px,0 1328px,0 3858px,0 4493px;  // 设置背景图在body中的位置 顺序为背景图片引入的顺序
  background-size: 100% 919px,100% 409px,100% 2530px,100% 635px,100% 355px;  // 设置背景图片的大小
}

```

#### 2. 对移动端适配要求不高的前提下，一种在不做移动端适配或不使用移动端框架的情况下，解决页面变形的方法，可以通过对视口标签meta的设置，达到简单解决的目的。

```html
- 视口宽度和设备保持一致
- 允许用户自行缩放
- 视口的默认缩放比例 0.3
- 最大允许的缩放比例 1.0
- 最小允许的缩放比例  0.3
<meta name="viewport" content="width=device-width, user-scalable=yes, initial-scale=0.3, maximum-scale=1.0, minimum-scale=0.3">
```

![image](https://user-images.githubusercontent.com/54464085/82140058-7fb36600-985f-11ea-95fb-cdbd40b2def2.png)
