### ISSUE TITLE
利用CSS动画属性简单实现动画暂停开始的效果

### ISSUE THREAD

**Issue by qqccyv** [qqccyv/blog#70]
![image](https://user-images.githubusercontent.com/54464085/143413386-faed6d36-0038-4486-b6a2-d5e37cf51541.png)
> 比如一些平常的长效loading效果
> 先定义一个简单的旋转效果的动画
```css
@keyframes rotateAnimate {
  0% {
    transform: rotate(0deg);
  }

  100% {
    transform: rotate(360deg);
  }
}
/* 设置到对应类名下面*/
  .icon {
      animation: rotateAnimate 2s linear infinite;
    }

/*设置两个类名，对应了暂停和运动*/
.active {
  animation-play-state: running !important;
}
.paused {
  animation-play-state: paused !important;
}

```
> 对应的html结构，vue项目,通过paused 变量控制动画的暂停和播放

```html
 <img class="right-icon-image"
                 :class="paused ? 'paused':'active'"
                 src="@/assets/images/refresh.png"
                 alt="">
```
